---

host_timezone: "Europe/Copenhagen"
appdata_path: /shares/storage/applications
appdata_path_server: /shares/storage/applications/odin

# ironicbadger.docker_compose_generator
docker_compose_generator_uid: "1000"
docker_compose_generator_gid: "1000"
docker_compose_generator_output_path: "/shares/storage/deployments/odin"

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: dnsutils
  - name: htop
  - name: net-tools
  - name: nmap
  - name: wget
  - name: pipx

# ironicbadger.bash-aliases
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dup", command: "docker-compose -f ~/docker-compose.yml -d " }
  - { alias: "dclean", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop" }  