services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    restart: unless-stopped
    labels:
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:28080]"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/dkaser/unraid-plugins/main/tsdproxy.png"
    ports:
      - "28080:8080"   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ appdata_path_server }}/tsdproxy:/data"
      - "{{ appdata_path_server }}/tsdproxy-config:/config"   