services:
  firefly_iii_core:
    image: fireflyiii/core:latest
    container_name: firefly_iii_core
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "budget"
      tsdproxy.container_port: {{ fireflyiii_port }}
    volumes:
      - "{{ appdata_path }}/firefly_iii_upload:/var/www/html/storage/upload"
    ports:
      - {{ fireflyiii_port }}:8080
    environment:
      DB_CONNECTION: pgsql
      DB_USERNAME:  "{{ PG_USER }}"
      DB_PASSWORD: "{{ PG_PASS }}"
      DB_HOST:  "{{ PG_HOST }}"
      DB_PORT: "{{ PG_PORT }}"
      DB_DATABASE: "{{ PG_DB_FIREFLY }}"
      TRUSTED_PROXIES: "{{ FIREFLY_TRUSTED_PROXIES }}"
      APP_KEY:  "{{ FIREFLY_APP_KEY }}"
