services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ appdata_path_server }}/tsdproxy:/data"
    environment:
      - TSDPROXY_AUTHKEY="{{ TSKEY_AUTH }}"
      - TSDPROXY_HOSTNAME="{{ TSDPROXY_HEIMDALL }}"
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
