services:
  actual-server:
    image: actualbudget/actual-server
    container_name: ActualServer
    environment:
      HOST_OS: Unraid
      HOST_HOSTNAME: Tower
      HOST_CONTAINERNAME: ActualServer
      TZ: Europe/Paris
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "actual"
      tsdproxy.ephemeral: "true"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:5006]"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/simonsickle/unraid-templates/main/teslamate/logo.png"
    volumes:
      - '{{appdata_path}}/actual-server:/data:rw'
    ports:
      - '5006:5006'