---
api:
  dashboard: true

ping: {}

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: edge-stack
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO

accessLog:
  filePath: /var/log/traefik/access.log
