services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - /shares/storage/applications/homepage:/app/config
    restart: unless-stopped