---
ansible_python_interpreter: /usr/bin/python3.12

docker_users:
  - aiml

packages_manage_ubuntu_sources: true
packages_ubuntu_codename: noble

compose_stack_wait_timeout: 180
compose_stack_extra_directories:
  - "{{ compose_stack_dest_dir }}/immich/libraries"
  - "{{ compose_stack_dest_dir }}/immich/photos"
  - "{{ compose_stack_dest_dir }}/immich/postgres-data"

nvidia_gpu_driver_version: "550.163.01"
nvidia_gpu_container_name: ollama
