---
- name: Copy the systemd service file for docker-compose
  become: yes
  template:
    src: docker-compose.service.j2
    dest: /etc/systemd/system/docker-compose.service
    mode: '0644'

- name: Reload systemd to read new service
  become: yes
  systemd:
    daemon_reload: yes

- name: Enable and start the docker-compose service
  become: yes
  systemd:
    name: docker-compose.service
    enabled: yes
    state: started
