# roles/ansible-role-update-system/tasks/main.yml

- name: Update APT package list
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade all APT packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Install python3 docker
  ansible.builtin.apt:
    name: python3-docker
    state: present

- name: Perform post-reboot tasks
  ansible.builtin.command: echo "Upgrade is done; playbook will continue"
  changed_when: false