services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "dashboard"
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: {{ homepage_port }}
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:{{ homepage_port }}]
      net.unraid.docker.icon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/android-chrome-512x512.png
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: {{ tailnet_domain_dashboard }}
    ports:
      - {{ homepage_port }}:3000
    volumes:
      - "{{ appdata_path }}/homepage:/app/config"
