---
dns_rewrite_entries:
  - domain: teslamate.ninik.lab
    answer: "{{ IP_TESLAMATE }}"
  - domain: teslamate-app.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: teslamate-grafana.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: dns.ninik.lab
    answer: "{{ IP_DNS }}"
  - domain: edge.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: homepage.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: homeassistant.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: immich.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: llama.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: nextcloud.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: traefik.ninik.lab
    answer: "{{ IP_EDGE }}"
  - domain: nas.local
    answer: "{{ IP_NAS }}"
  - domain: tower.local
    answer: "{{ IP_TOWER }}"
  - domain: fat-lady.internal
    answer: "{{ IP_FAT_LADY }}"
  - domain: homeassistant.local
    answer: "{{ IP_HOMEASSISTANT }}"
  - domain: monitoring.ninik.lab
    answer: "{{ IP_MONITORING }}"
  - domain: nas.ninik.lab
    answer: "{{ IP_NAS }}"
  - domain: pbs.ninik.lab
    answer: "{{ IP_PBS }}"
  - domain: pve2.ninik.lab
    answer: "{{ IP_PVE2 }}"
  - domain: tsd.ninik.lab
    answer: "{{ IP_EDGE }}"
