---
docker_hosts:
  - name: DNS
    host: "{{ IP_DNS }}"
  - name: Monitoring
    host: "{{ IP_MONITORING }}"
  - name: TeslaMate
    host: "{{ IP_TESLAMATE }}"
  - name: AIML
    host: "{{ IP_AIML }}"
  - name: Nextcloud
    host: "{{ IP_NEXTCLOUD }}"
