---
# TODO: vault this secret before the first real deployment.
compose_stack_extra_directories:
  - "{{ compose_stack_dest_dir }}/traefik/logs"
  - "{{ compose_stack_dest_dir }}/homepage/data"
  - "{{ compose_stack_dest_dir }}/tsdproxy/data"
  - "{{ compose_stack_dest_dir }}/tsdproxy/secrets"
compose_stack_secret_files:
  - dest: "{{ compose_stack_dest_dir }}/tsdproxy/secrets/tailscale-authkey"
    content: "{{ EDGE_TAILSCALE_AUTHKEY }}"
    mode: "{{ compose_stack_secret_file_default_mode }}"

####### LOCAL domains
local_traefik_domain: traefik.ninik.lab
LOCAL_HOMEPAGE_DOMAIN: homepage.ninik.lab
docker_hosts:
  - name: DNS
    host: "{{ IP_DNS }}"
    port: 2375
    target_hostname: "{{ IP_DNS }}"
  - name: Monitoring
    host: "{{ IP_MONITORING }}"
    port: 2375
    target_hostname: "{{ IP_MONITORING }}"
  - name: TeslaMate
    host: "{{ IP_TESLAMATE }}"
    port: 2375
    target_hostname: "{{ IP_TESLAMATE }}"
  - name: AIML
    host: "{{ IP_AIML }}"
    port: 2375
    target_hostname: "{{ IP_AIML }}"
  - name: NAS
    host: "{{ IP_NAS }}"
    port: 2375
    target_hostname: "{{ IP_NAS }}"
remote_http_services:
  - name: teslamate
    host: "{{ IP_TESLAMATE }}"
    port: 4000
    domain: teslamate-app.ninik.lab
  - name: teslamate-grafana
    host: "{{ IP_TESLAMATE }}"
    port: 3000
    domain: teslamate-grafana.ninik.lab
  - name: homeassistant
    host: "{{ IP_HOMEASSISTANT }}"
    port: 8123
    domain: homeassistant.ninik.lab
  - name: immich
    host: "{{ IP_AIML }}"
    port: 8080
    domain: immich.ninik.lab
