---
remote_http_domain_suffix: .ninik.lab
remote_http_services:
  - hostname: teslamate-app
    host: "{{ IP_TESLAMATE }}"
    port: 4000
  - hostname: teslamate-grafana
    host: "{{ IP_TESLAMATE }}"
    port: 3000
  - hostname: homeassistant
    host: "{{ IP_HOMEASSISTANT }}"
    port: 8123
  - hostname: immich
    host: "{{ IP_AIML }}"
    port: 8080
  - hostname: llama
    host: "{{ IP_AIML }}"
    port: 11434
  - hostname: nextcloud
    host: "{{ IP_NEXTCLOUD }}"
    port: 8080
