- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/NeK000/homelab'
    dest: /tmp/applications

- name: Deploy portainer agent
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent
    state: started
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
