services:
  teslamate:
    image: teslamate/teslamate:latest
    container_name: teslamate
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "teslamate"
      tsdproxy.container_port: {{ teslamate_port }}
    volumes:
      - "{{ appdata_path }}/teslamate/./import:/opt/app/import"
    ports:
      - {{ teslamate_port }}:4000
    environment:
      ENCRYPTION_KEY: "{{ TESLAMATE_ENCRYPTION_KEY }}"
      DATABASE_USER: "{{ TESLAMATE_PG_USER }}"
      DATABASE_PASS: "{{ TESLAMATE_PG_PASS }}"
      DATABASE_NAME: "{{ TESLAMATE_PG_DB }}"
      DATABASE_HOST: "{{ TESLAMATE_PG_HOST }}"
      MQTT_HOST: "{{ TESLAMATE_MQTT_HOST }}"
      MQTT_USERNAME: "{{ TESLAMATE_MQTT_USERNAME }}"
      MQTT_PASSWORD: "{{ TESLAMATE_MQTT_PASSWORD }}"
    cap_drop:
      - all
    restart: always
  grafana:
    image: teslamate/grafana:latest
    container_name: teslamate-grafana
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "teslamate-grafana"
      tsdproxy.container_port: {{ teslamate_grafana_port }}
    volumes:
      - "{{ appdata_path }}/teslamate/grafana-data:/var/lib/grafana"
    ports:
      - {{ teslamate_grafana_port }}:3000
    environment:
      DATABASE_USER: "{{ TESLAMATE_PG_USER }}"
      DATABASE_PASS: "{{ TESLAMATE_PG_PASS }}"
      DATABASE_NAME: "{{ TESLAMATE_PG_DB }}"
      DATABASE_HOST: "{{ TESLAMATE_PG_HOST }}"
    restart: always