---
services:

  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: pdf
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "pdf"
      tsdproxy.container_port: 18080
    ports:
      - 18080:8080
