services:
  calligra:
    image: lscr.io/linuxserver/calligra:latest
    container_name: calligra
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "calligra"
      tsdproxy.container_port: {{ calligra_tailscale_port }}    
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes: 
      - /path/to/config:/config
    ports:
      - {{ calligra_tailscale_port }}:3000
    restart: unless-stopped    