services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: pdf
    restart: always
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "pdf"
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: {{ pdf_port }}
    ports:
      - {{ pdf_port }}:8080
