- name: Create mount point
  ansible.builtin.file:
    path: /shares/storage
    state: directory
  become: true

- name: Ensure NFS entry is in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: 'fat-lady.internal:/mnt/user/pidata /shares/storage nfs noauto,nofail,x-systemd.automount,x-systemd.device-timeout=90 0 0'
    state: absent

- name: Mount NFS Share
  ansible.posix.mount:
    path: /shares/storage
    src: fat-lady.internal:/mnt/user/pidata
    fstype: nfs
    opts: rw,sync,hard
    state: mounted
  become: true

- name: Ensure directory has correct permissions
  block:
    - name: Add test file for permission check
      ansible.builtin.file:
        path: /shares/storage/testfile
        state: touch
        mode: '0777'

    - name: Check directory permissions
      ansible.builtin.stat:
        path: /shares/storage
      register: dir_permissions

    - name: Set directory permissions if needed
      ansible.builtin.file:
        path: /shares/
        mode: '0777'
      when: dir_permissions.stat.mode != '0777'

    - name: Remove test file
      ansible.builtin.file:
        path: /shares/storage/testfile
        state: absent
