services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    restart: unless-stopped
    ports:
      - "28080:8080"   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ appdata_path_server }}/tsdproxy:/data"
      - "{{ appdata_path_server }}/tsdproxy-config:/config"   