services:
  app:
    image: fireflyiii/core:latest
    container_name: firefly_iii_core
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "budget"
      tsdproxy.container_port: {{ fireflyiii_port }}
    volumes:
      - "{{ appdata_path }}/firefly_iii_upload:/var/www/html/storage/upload"
    ports:
      - {{ fireflyiii_port }}:8080
    environment:
      DB_CONNECTION: pgsql
      DB_USERNAME:  "{{ MEALIE_PG_USER }}"
      DB_PASSWORD: "{{ FIREFLY_PG_PASS }}"
      DB_HOST:  "{{ FIREFLY_PG_HOST }}"
      DB_PORT: "{{ FIREFLY_PG_PORT }}"
      DB_DATABASE: "{{ FIREFLY_PG_DB }}"
      TRUSTED_PROXIES: "{{ FIREFLY_TRUSTED_PROXIES }}"
      APP_KEY:  "{{ FIREFLY_APP_KEY }}"
    restart: on-failure:10
