services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: Immich_Application
    environment:
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Tower
      - HOST_CONTAINERNAME=immich
      - DB_HOSTNAME={{ IMMICH_ADDRESS }}
      - DB_PORT={{IMMICH_DB_PORT}}
      - DB_USERNAME=postgres
      - DB_PASSWORD={{ IMMICH_DB_PASSWORD }}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME={{ IMMICH_ADDRESS }}
      - REDIS_PORT=6379
      - REDIS_PASSWORD= ''
      - MACHINE_LEARNING_HOST= 0.0.0.0
      - MACHINE_LEARNING_PORT= 3003
      - MACHINE_LEARNING_WORKERS= 1
      - MACHINE_LEARNING_WORKER_TIMEOUT= 120
      - PUID= 99
      - PGID= 100
      - UMASK= 022
    labels:
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8080]"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png"
      tsdproxy.enable: "true"
      tsdproxy.name: "immich"
      tsdproxy.container_port: 8080
      tsdproxy.ephemeral: "true"
    ports:
      - '8080:8080'
    volumes:
      - '{{appdata_path}}/immich/photos:/photos:rw'
      - '{{appdata_path}}/immich/libs:/libraries:rw'
      - '{{appdata_path}}/immich:/config:rw'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Use all available GPUs
              capabilities: [gpu]


  postgresql_immich:
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    container_name: PostgreSQL_Immich
    environment:
      - TZ= Europe/Paris
      - HOST_OS= Unraid
      - HOST_HOSTNAME= Tower
      - HOST_CONTAINERNAME= PostgreSQL_Immich
      - POSTGRES_PASSWORD= {{ IMMICH_DB_PASSWORD }}
      - POSTGRES_USER= postgres
      - POSTGRES_DB= immich
    labels:
      net.unraid.docker.managed: "dockerman"
    volumes:
      - '{{appdata_path}}/PostgreSQL_Immich:/var/lib/postgresql/data:rw'
    ports:
      - '{{IMMICH_DB_PORT}}:5432'

      
  immich-redis:
    image: redis
    container_name: Immich-Redis
    environment:
      - TZ= Europe/Paris
      - HOST_OS= Unraid
      - HOST_HOSTNAME= Tower
      - HOST_CONTAINERNAME= Immich-Redis
    ports:
      - '6379:6379'