## SERVERS
[pve2]
pve2.ninik.lab ansible_host=10.50.10.50 ansible_ssh_user=root

[pbs]
pbs.ninik.lab ansible_ssh_user=root

## LXCs
[edge]
edge.ninik.lab ansible_host=10.50.10.210 ansible_ssh_user=root

[dns]
dns.ninik.lab ansible_host=10.50.10.212 ansible_ssh_user=root

[monitoring]
monitoring.ninik.lab ansible_host=10.50.10.213 ansible_ssh_user=root

[teslamate]
teslamate.ninik.lab ansible_host=10.50.10.211 ansible_ssh_user=root

[aiml]
aiml.ninik.lab ansible_host=10.50.10.214 ansible_ssh_user=root