---
  - hosts: aiml
    roles:
      - role: packages
      - role: geerlingguy.docker
      - role: nvidia_gpu
      - role: compose_stack
        tags:
          - compose

  - hosts: edge
    roles:
      - role: packages
      - role: geerlingguy.docker
      - role: compose_stack
        tags:
          - compose

  - hosts: dns
    roles:
      - role: packages
      - role: geerlingguy.docker
      - role: dns_host_prepare
      - role: compose_stack
        tags:
          - compose
      - role: adguard_config
        tags:
          - dns_rewrites

  - hosts: monitoring
    roles:
      - role: packages
      - role: geerlingguy.docker
      - role: compose_stack
        tags:
          - compose

  - hosts: teslamate
    roles:
      - role: packages
      - role: geerlingguy.docker
      - role: compose_stack
        tags:
          - compose

  - hosts: nextcloud
    roles:
      - role: packages
      - role: geerlingguy.docker
      - role: compose_stack
        tags:
          - compose
