services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0
    container_name: mealie
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "recipes"
      tsdproxy.container_port: 19000
    volumes:
      - /shares/storage/applications/mealie:/app/data
    ports:
      - 19000:9000
    environment:
      ALLOW_SIGNUP: true
      DB_ENGINE: postgres
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_SERVER: ${PG_HOST}
      POSTGRES_PORT: ${PG_PORT}
      POSTGRES_DB: ${PG_DB}
    restart: unless-stopped
