services:
  duplicati:
    container_name: duplicati
    image: duplicati/duplicati:2.1.0.118
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "duplicati"
      tsdproxy.ephemeral: "true"
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:8200]
      net.unraid.docker.icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/duplicati-logo.png
    environment:
      SETTINGS_ENCRYPTION_KEY: "{{SETTINGS_ENCRYPTION_KEY}}"
      DUPLICATI__WEBSERVICE_PASSWORD: "{{DUPLICATI__WEBSERVICE_PASSWORD}}"
    volumes:
      - /mnt/user/duplicati:/data
      - /mnt/user/appdata:/mnt
    ports:
      - "8200:8200"