services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - 58090:8090
    volumes:
      - "{{ appdata_path }}/beszel_data:/beszel_data"
    extra_hosts:
      - 'host.docker.internal:host-gateway'