services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "drawio"
      tsdproxy.container_port: {{ drawio_port }}
    ports:
      - {{ drawio_port }}:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s