services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:release
    restart: unless-stopped
    container_name: karakeep
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "karakeep"
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: "3000"
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3000]
      net.unraid.docker.icon: https://raw.githubusercontent.com/Collectathon/unraid-templates/main/icons/hoarder.png
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - "{{ appdata_path }}/karakeep/data:/data"
    ports:
      - 3000:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      NEXTAUTH_SECRET: "{{NEXTAUTH_SECRET}}"
      NEXTAUTH_URL: http://localhost:3000
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    container_name: karakeep_chrome
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: https://raw.githubusercontent.com/Collectathon/unraid-templates/main/icons/hoarder.png
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    container_name: karakeep_meilisearch
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: https://raw.githubusercontent.com/Collectathon/unraid-templates/main/icons/hoarder.png
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      MEILI_MASTER_KEY: "{{MEILI_MASTER_KEY}}"
      MEILI_NO_ANALYTICS: "true"

    volumes:
      - "{{ appdata_path }}/karakeep/meilisearch:/meili_data"
