services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "dashboard"
      tsdproxy.container_port: {{ homepage_port }}
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: {{ tailnet_domain_dashboard }}
    ports:
      - {{ homepage_port }}:3000
    volumes:
      - "{{ appdata_path }}/homepage:/app/config"
