services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "beszel"
      tsdproxy.container_port: {{ beszel_port }}
    ports:
      - {{ beszel_port }}:8090
    volumes:
      - "{{ appdata_path }}/beszel_data:/beszel_data"
    extra_hosts:
      - 'host.docker.internal:host-gateway'