services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0
    container_name: mealie
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "recipes"
      tsdproxy.container_port: {{ mealie_port }}
    volumes:
      - "{{ appdata_path }}/mealie:/app/data"
    ports:
      - {{ mealie_port }}:9000
    environment:
      ALLOW_SIGNUP: true
      DB_ENGINE: postgres
      POSTGRES_USER: "{{ MEALIE_PG_USER }}"
      POSTGRES_PASSWORD: "{{ MEALIE_PG_PASS }}"
      POSTGRES_SERVER: "{{ MEALIE_PG_HOST }}"
      POSTGRES_PORT: "{{ MEALIE_PG_PORT }} "
      POSTGRES_DB: "{{ MEALIE_PG_DB }}"
    restart: on-failure:10
