services:
  traefik:
    image: traefik
    container_name: traffic
    volumes:
      - "{{ appdata_path }}/traefik/letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    # environment:
      # CLOUDFLARE_EMAIL: "{{ CLOUDFLARE_MAIL_ADDRESS }}"
      # CLOUDFLARE_API_KEY: "{{ CLOUDFLARE_API_KEY }}"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedByDefault=false"  # Disable auto-exposing containers
      - "--serverstransport.insecureskipverify=true" # Avoid HTTPS enforcement
      - "--log.level=INFO"